# Whiteboard Configuration
## Docs: https://hexo.io/docs/configuration.html

# Site
title: Newbie Dev Documentation
subtitle:
description:
author: Duc Dao
language: vi_VN
timezone: UTC-7

# URL (Used when deploying)
url: http://docs.newbie-dev.net
root: /

# Directory
source_dir: source
public_dir: public
relative_link: true
future: true

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Whiteboard theme
theme: whiteboard

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/dhduc/whiteboard
  branch: master
